chore: Replace `doc_auto_cfg` with `doc_cfg` (#1664)
- [ ] Added a `CHANGELOG.md` entry

# Summary

Replace the removed `doc_auto_cfg` feature with the `doc_cfg` feature.

# Motivation

Avoid compilation errors when building documentation.

# Details

`doc_auto_cfg` was merged into `doc_cfg` in rust-lang/rust#138907.

When `docsrs` is enabled, the old `doc_auto_cfg` results in the
following errors on the latest nightlies:

```
error[E0557]: feature has been removed
  --> src/lib.rs:56:29
   |
56 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
   |                             ^^^^^^^^^^^^ feature has been removed
   |
   = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
   = note: merged into `doc_cfg`
```

```
error[E0557]: feature has been removed
  --> rand_core/src/lib.rs:36:29
   |
36 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
   |                             ^^^^^^^^^^^^ feature has been removed
   |
   = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
   = note: merged into `doc_cfg`
```

The new `doc_cfg` retains the automatic `cfg` generation that
`doc_auto_cfg` used to provide.